---
version: '2.3'

services:
  kubectl:
    image: lachlanevenson/k8s-kubectl:v1.9.6
    working_dir: /app
    volumes:
      - ".:/app"
      - "$HOME/.kube:/root/.kube"
      - "$HOME/.aws:/root/.aws"

  kt:
    image: myobplatform/kt:0.2.3
    volumes:
      - "$HOME/.kube:/root/.kube"
      - ".:/app"
