---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-commander
  namespace: platform-enablement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
        tier: backend
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander
        env:
        - name: REDIS_HOSTS
          value:
        ports:
        - name: redis-commander
          containerPort: 8081
