---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-commander
  namespace: platform-enablement
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        env:
        - name: REDIS_HOSTS
          value: redis-instance1:kube-redis:6379
        ports:
        - name: redis-commander
          containerPort: 8081
