---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $config.kube-redis.name }}-rb
  labels:
    app: {{ $config.kube-redis.name }}
    repo: kube-redis
    deployed-with: kt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $config.kube-redis.name }}-rb
subjects:
- kind: ServiceAccount
  name: {{ $config.kube-redis.name }}
  namespace: {{ $config.kube-redis.namespace }}
