{{ $config := (datasource "config") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.kube-redis.name }}
  namespace: {{ $config.kube-redis.namespace }}
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
