{{ $config := (datasource "config") }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{ $config.kube-redis.name }}
    repo: kube-redis
  name: {{ $config.kube-redis.name }}
  namespace: {{ $config.kube-redis.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ $config.kube-redis.pvAz }}
  resources:
    requests:
      storage: "1Gi"
