{{ $config := (datasource "config") }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $config.kubeRedis.name }}
    repo: kube-redis
    deployed-with: kt
  name: {{ $config.kubeRedis.name }}
  namespace: {{ $config.kubeRedis.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: {{ $config.kubeRedis.name }}
    repo: kube-redis
    deployed-with: kt
