---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-redis
    repo: kube-redis
    deployed-with: kt
  name: kube-redis
  namespace: {{ $config.kube-redis.namespace }}
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 9090
  selector:
    app: kube-redis
    repo: kube-redis
    deployed-with: kt
  type: "ClusterIP"
