{{ $config := (datasource "config") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $config.kubeRedis.name }}
  namespace: {{ $config.kubeRedis.namespace }}
  labels:
    app: {{ $config.kubeRedis.name }}
    repo: kube-redis
    deployed-with: kt
