---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $config.kube-redis.name }}
  namespace: {{ $config.kube-redis.namespace }}
  labels:
    app: {{ $config.kube-redis.name }}
    repo: kube-redis
    deployed-with: kt
