{{ $config := (datasource "config") }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $config.kube-redis.name }}
    repo: kube-redis
    deployed-with: kt
  name: {{ $config.kube-redis.name }}
  namespace: {{ $config.kube-redis.namespace }}
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 9090
  selector:
    app: {{ $config.kube-redis.name }}
    repo: kube-redis
    deployed-with: kt
  type: "ClusterIP"
