---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: redis-operator
    repo: kube-redis
  name: redis.myob.com
spec:
  group: myob.com
  version: v1alpha1
  names:
    kind: Redis
    listKind: RedisList
    plural: redis
  scope: Namespaced
