---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-operator-user
rules:
  - apiGroups:
      - "myob.com"
    resources:
      - redis
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
